name: DirectAuction
author: SemTeul
main: semteul\directauction\DirectAuction
api: [1.12.0]
version: "0.2"
permissions:
  directauction:
    description: "DirectAuction command"
    default: true